package com.utils;

import java.util.ArrayList;

public class Constants {

    public static String URL = "Url";
    public static final String LIVE_MINT = "LiveMint";
    public static final String LIVEMINT = "Live Mint";
    public static final String ANDROID = "android";
    public static final String IOS = "ios";
    public static final String WEB = "web";
    public static final String PLATFORM = "platform";
    public static final String PROJECT_ID = "projectId";
    public static final String PROJECT_NAME = "projectName";
    public static final String APPLICATION_TYPE = "applicationType";
    public static final String SANITY_RUN = "sanityRun";
    public static final String SMOKE_RUN = "smokeRun";
    public static final String REGRESSION_RUN = "RegressionRun";
    public static final String SANITY = "sanity";
    public static final String PRODUCTION = "production";
    public static final String REGRESSION = "regression";


    public static final String BROWSER = "browser";
    public static final String BROWSER_TYPE = "browserType";
    public static final String BROWSER_VERSION = "browserVersion";

    public static final String APP = "app";

    public static final String DEVICE_NAME_ANDROID = "deviceNameAndroid";
    public static final String PLATFORM_VERSION_ANDROID = "platformVersionAndroid";
    public static final String APPIUM_SERVER_IP = "appiumServerIp";
    public static final String APPIUM_SERVER_PORT = "appiumServerPort";
    public static final String DEVICE_NAME_IOS = "deviceNameIOS";
    public static final String PLATFORM_VERSION_IOS = "platformVersionIOS";
    public static final String IPA_FILE_NAME = "ipaFileName";
    public static final String UDID = "udid";
    public static final String JIRA_PROJECT_NAME = "jiraProjectName";
    public static final String JIRA_DEFECT_TYPE = "defectType";
    public static final String XCODE_ORG_ID = "xcodeOrgId";
    public static final String XCODE_SIGNING_ID = "xcodeSigningId";
    public static final String UPDATE_WDA_BUNDLE_ID = "updateWDABundleId";
    public static final String CONNECT_HARDWARE_KEYBOARD = "connectHardwareKeyboard";
    public static final String AUTOMATION_NAME = "automationname";
    public static final String JIRA_URL = "jiraURL";
    public static final String JIRA_USERNAME = "jiraUserName";
    public static final String JIRA_PASSWORD = "jiraPassword";
    public static final String IS_CREATE_BUG = "isCreateBug";
    public static final String MAX_RETRY = "maxTry";
    public static final String SENDER_EMAIL_ID = "senderEmailId";
    public static final String SENDER_EMAIL_PASSWORD = "senderEmailPassword";
    public static String REPORT_PATH = "";
    public static String REPORT_NAME = "";

    public static ArrayList<String> TEST_RESULT_COUNT = new ArrayList<String>();
    public static final String MAIL_RECIPIENT = "mailRecipient";
    public static final String JIRA_FLAG = "raiseIssue";
    public static final String MAIL_FLAG = "sendMail";
    public static final String EXECUTION_TYPE = "executionType";

    public static final String DEVICE_NAME = "deviceName";
    public static final String DEVICE = "device";
    public static final String PLATFORM_VERSION = "platformVersion";
    public static final String PLATFORM_NAME = "platformName";
    public static final String NEW_COMMAND_TIMEOUT = "newCommandTimeout";
    public static final String LOCATION_SERVICES_AUTHORIZED = "locationServicesAuthorized";
    public static final String AUTO_GRANT_PERMISSIONS = "autoGrantPermissions";
    public static final String ANDROID_APK_FILE_NAME = "androidAPKFileName";
    public static final String APP_PACKAGE = "appPackage";
    public static final String APP_ACTIVITY = "appActivity";
    public static final String APP_WAIT_PACKAGE = "appWaitPackage";
    public static final String BUNDLE_ID = "bundleId";
    public static final String IS_CLOUD_RUN = "isCloudRun";
    public static final String IS_AUTO_START_APPIUM = "isAutoStartAppium";
    public static final String JIRA_DEFECT_ASSIGNEE = "jiraDefectAssignee";
    public static final String UAT_URL = "uatUrl";
    public static final String STG_URL = "stgUrl";
    public static final String AUT_URL = "autUrl";
    public static final String QA_URL = "qaUrl";
    public static final String QA_AMP_URL = "qaAmpUrl";
    public static final String STG_AMP_URL = "stgAMPUrl";
    public static final String PRE_PROD_AMP_URL = "preProdAMPUrl";
    public static final String PRE_PROD_URL = "preProdUrl";
    public static final String PROD_URL = "prodUrl";
    public static final String AMP_URL = "ampUrl";
    public static final String ENVIRONMENT = "environment";
    public static final String WEB_DRIVER_CHROME = "webdriver.chrome.driver";
    public static final String YES = "yes";
    public static final String NO = "no";
    public static final String SKIP = "skip";
    public static final String IMPLICIT_WAIT = "implicitWait";
    public static final String CLASS = "class";
    public static final String RESULTED = "resulted";
    public static final String NO_RESET = "noReset";
    public static final String FALSE = "false";
    public static final String DESKTOP = "desktop";
    public static final String AMP = "amp";
    public static final String MOBILE_BROWSER = "Mobile Browser";
    public static final String ERROR = "error";
    public static final String TRUE = "true";
    public static final String NATIVE = "native";
    public static final String GENERAL_CONFIG = "GeneralConfig";
    public static final String PROJECT_DETAILS = "ProjectDetails";

    public static final String DESKTOP_WEB = "desktop_web";
    public static final String ANDROID_WEB = "android_web";
    public static final String IOS_WEB = "ios_web";
    public static final String ANDROID_AMP = "android_amp";
    public static final String IOS_AMP = "ios_amp";
    public static final String ANDROID_NATIVE = "android_native";
    public static final String IOS_NATIVE = "ios_native";
    public static final String CHROME = "chrome";
    public static final String FIREFOX = "firefox";
    public static final String OPERA = "opera";
    public static final String IE = "ie";

    public static final String USERNAME = "username";
    public static final String ACCESS_KEY = "access_key";
    public static final String PROJECT = "project";
    public static final String BROWSER_STACK_NAME = "browserStackName";
    public static final String BROWSER_STACK_BROWSER = "browserStackBrowser";
    public static final String BROWSER_STACK_DEBUG = "browserStackDebug";
    public static final String BUILD = "build";

    public static final String SMART_CAST = "SmartCast";
    public static final String HINDUSTAN_TIMES = "HindustanTimes";
    public static final String BLANK_PAPER = "BlankPaper";
    public static final String LIVE_HINDUSTAN = "LiveHindustan";
    public static final String HT_E_PAPER = "HT_Epaper";
    public static final String LM_E_PAPER = "LM_Epaper";
    public static final String LH_E_PAPER = "LH_Epaper";
    public static final String HT_AUTO = "HT_AUTO";
    public static final String HT_TECH = "HT_TECH";
    public static final String HEALTH_SHOTS= "Healthshots";

    public static final String STORY_HEADLINE = "Lorem !psum dolor $%':@met, con&ectetur adipiscing %lit. Suspendis 'quis velit:";
    public static final String STORY_KEYWORD = "dolor";
    public static final String STORY_Min = "L";
    public static final String STORY_Max = "Lorem !psum dolor $%':@met, con&ectetur adipiscing %lit. Suspendis 'quis velit:";
    public static final String regExSpecialChars = "$%':@";
    public static final String REGEX = "[^a-zA-Z0-9]+";
    public static final String HINDI = "Hindi";
    public static final String TECH = "Tech";
    public static final String BANGLA = "Bangla";
    public static final String AUTO = "Auto";
    public static final String SMART_24 = "Smart 24";
    public static final String MINT_LOUNGE = "Mint Lounge";
    public static final String HT_NEW = "HT NEW";
    public static final String HT_LIVEBLOG = "HT-LiveBlog";
    public static final String TEST_CONFIG_WEB = "TestConfig_Web";
    public static final String TEST_CONFIG_NATIVE= "TestConfig_Native";
    public static final String NA = "N/A";
    public static final String SPREADSHEET_ID = "spreadsheetId";
    public static final String PROD = "prod";
    public static final String VIDEO_PREVIEW_POPUP_CREATED = "Created In BrightCove On";
    public static final String VIDEO_PREVIEW_POPUP_CHANNEL = "Channel";
    public static final String VIDEO_PREVIEW_POPUP_TAGS = "Tags";
    public static final String AUT = "aut";
    public static final String STG = "stg";
    public static final String QA = "qa";

    public static final String QA_MONGO_DB_URI_HT = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/cms-backend?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_HT_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/ht-qa?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_SMART24_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/smart-24?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_AUTO_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/ht-auto?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_TECH_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/ht-tech?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_ML_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/mintlounge?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_LM_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/livemint?authSource=admin&replicaSet=blank-stg";
    public static final String QA_MONGO_DB_URI_BANGLA_QA = "mongodb://blankpaper:blanKpApErSTG@10.136.172.237,10.136.172.195,10.136.172.57/ht-bangla?authSource=admin&replicaSet=blank-stg";
    public static final String STAGING_MONGO_DB_URI_HT = "mongodb://ht-live-blog:HTmeD!%40896@10.137.166.63:27017,10.137.166.43:27017,10.137.166.43:27018/?authSource=ht-live-blog&replicaSet=authors-stg";
    public static final String BACKEND_STAGING_MONGO_DB_URI_HT = "mongodb://cmsstg:cmsstgmongo@10.136.172.10:27017,10.136.172.11:27017,10.136.172.12:27018/cms-backend?%20authSource=cms-backend&replicaSet=htcms";
    public static final String BACKEND_STAGING_MONGO_DB_URI_BANGLA = "mongodb://cms-ht-bengali:bengalicms4321@10.136.172.10:27017,10.136.172.11:27017,10.136.172.12:27018/?replicaSet=htcms&authSource=cms-ht-bengali";
    public static final String QA_MONGO_DB_DATABASE_HT = "ht-qa";

    public static final String QA_MONGO_DB_DATABASE_SMART24 = "smart-24";
    public static final String QA_MONGO_DB_DATABASE_LM = "livemint";
    public static final String QA_MONGO_DB_DATABASE_BANGLA = "ht-bangla";
    public static final String QA_MONGO_DB_DATABASE_AUTO = "ht-auto";
    public static final String QA_MONGO_DB_DATABASE_TECH = "ht-tech";
    public static final String QA_MONGO_DB_DATABASE_MINT_LOUNGE = "mintlounge";
    public static final String BACKEND_QA_MONGO_DB_DATABASE_HT = "cms-backend";
    public static final String STAGING_MONGO_DB_DATABASE_HT = "ht-live-blog";
    public static final String STAGING_MONGO_DB_DATABASE_BANGLA = "cms-ht-bengali";
    public static final String BACKEND_STAGING_MONGO_DB_DATABASE_HT = "cms-backend";
    public static final String QA_MONGO_DB_COLLECTION_HT = "cms_article_master_v6";
    public static final String STAGING_MONGO_DB_COLLECTION_BANGLA = "cms_article_master_v6";
    public static final String BACKEND_QA_MONGO_DB_COLLECTION_HT = "cms_article_v6";
    public static final String STAGING_MONGO_DB_COLLECTION_HT = "cms_article_master_v6";
    public static final String BACKEND_STAGING_MONGO_DB_COLLECTION_HT = "cms_article_v6";
    public static final String SSO = "SSO";
    public static final String URL_LIVEBLOG = "urlLiveBlog";
    public static final String URL_CTALOGO = "urlCTALogo";
}
